baseURL = "https://halalchain.github.io/docs"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "Qitmeer Documentation"
theme = "qitmeer-doc"
themesdir = "./themes/"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

[params]
  editURL = "https://github.com/HalalChain/docs/edit/master/Document/content/"
  viewURL = "https://github.com/HalalChain/docs/tree/master/Document/content/"
  issueURL = "https://github.com/HalalChain/docs/issues/new"
  description = "Documentation for Hugo qitmeer-doc"
  author = "Mathieu Cornic"
  showVisitedLinks = false
  disableBreadcrumb = false
  disableNextPrev = false
  themeVariant = "mine"

[outputs]
home = [ "HTML", "RSS", "JSON"]


# [Languages]
[Languages]
[Languages.cn]
title = "Qitmeer 文档"
weight = 1
languageName = "中文（简体）"

[Languages.en]
title = "Qitmeer Documentation"
weight = 1
languageName = "English"

[Languages.ar]
title = "Qitmeer ملفات"
weight = 1
languageName = "العربية"



# [[Languages.en.menu.shortcuts]]
# name = "<i class='fab fa-fw fa-github'></i> GitHub repo"
# identifier = "ds"
# url = "https://github.com/matcornic/hugo-theme-learn"
# weight = 10


# [[Languages.cn.menu.shortcuts]]
# name = "<i class='fab fa-fw fa-github'></i> GitHub repo"
# identifier = "ds"
# url = "https://github.com/matcornic/hugo-theme-learn"
# weight = 10
